version: 2.1
jobs:
  build:
    working_directory: ~/jupiter
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: test
          command: npm ApiCall