version: 2.1
jobs:
  build:
    working_directory: ~/jupiter
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install xmlhttp
          command: 'sudo npm install xmlhttprequest'
      - run:
          name: test2
          command: node ApiCall.js
